// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniERP.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniERP.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319175959_SeedData2")]
    partial class SeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniERP.API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "85 Rue du Docteur Bauer, 93400 Saint-Ouen",
                            DateCreation = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            NomEntreprise = "Gaming Campus",
                            Siret = "12345678900001"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "6 Rue de la Rabotière, 44800 Saint-Herblain",
                            DateCreation = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NomEntreprise = "Proginov",
                            Siret = "33298227200034"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "12 Rue de la Paix, 75002 Paris",
                            DateCreation = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            NomEntreprise = "Studio Pixel",
                            Siret = "98765432100012"
                        });
                });

            modelBuilder.Entity("MiniERP.API.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NumeroFacture")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("MiniERP.API.Models.LigneFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FactureId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<decimal>("Remise")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("MiniERP.API.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Licence Unity Pro (1 an)",
                            PrixUnitaireHT = 1800.00m,
                            Reference = "LIC-UNITY"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Formation C# Avancé (5 jours)",
                            PrixUnitaireHT = 3500.00m,
                            Reference = "FORM-CSHARP"
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Développement site web vitrine",
                            PrixUnitaireHT = 2500.00m,
                            Reference = "DEV-WEB"
                        },
                        new
                        {
                            Id = 4,
                            Designation = "Contrat de maintenance annuel",
                            PrixUnitaireHT = 1200.00m,
                            Reference = "MAINT-ANNUELLE"
                        },
                        new
                        {
                            Id = 5,
                            Designation = "Hébergement Cloud Pro (1 an)",
                            PrixUnitaireHT = 600.00m,
                            Reference = "HOSTING-PRO"
                        });
                });

            modelBuilder.Entity("MiniERP.API.Models.Facture", b =>
                {
                    b.HasOne("MiniERP.API.Models.Client", "Client")
                        .WithMany("Factures")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MiniERP.API.Models.LigneFacture", b =>
                {
                    b.HasOne("MiniERP.API.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniERP.API.Models.Produit", "Produit")
                        .WithMany("LignesFacture")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("MiniERP.API.Models.Client", b =>
                {
                    b.Navigation("Factures");
                });

            modelBuilder.Entity("MiniERP.API.Models.Facture", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("MiniERP.API.Models.Produit", b =>
                {
                    b.Navigation("LignesFacture");
                });
#pragma warning restore 612, 618
        }
    }
}
